"use client";
import {motion} from "framer-motion";
import {community} from "../data/community";
const label:any={done:["REALIZADA","ok"],next:["PRÓXIMA","warn"],pending:["PENDIENTE","danger"],ondemand:["A REQUERIMIENTO","muted"]};
export default function Home(){return <main>
<section className="hero"><div className="orb orb1"/><div className="orb orb2"/><nav><div className="brand"><span className="mark">O</span><span>ORBI <b>CONDO</b></span></div><span className="pilot">EXPERIENCIA PC2 · 2026</span></nav><motion.div className="heroCopy" initial={{opacity:0,y:28}} animate={{opacity:1,y:0}} transition={{duration:.8}}><p className="eyebrow">PARQUE CIUDADANO II · RANCAGUA</p><h1>Tu condominio,<br/><em>más claro.</em></h1><p className="lead">Descubre qué se mantiene, quién lo cuida y qué viene después. Toda la información esencial de tu comunidad, transformada en una experiencia que cualquiera puede entender.</p><div className="actions"><a href="#maintenance" className="primary">Explorar mantenciones <span>↓</span></a><span className="live"><i/> Información comunitaria</span></div></motion.div><div className="heroStats"><div><b>09</b><span>Sistemas</span></div><div><b>05</b><span>Proveedores</span></div><div><b>04</b><span>Certificaciones</span></div><div><b>365</b><span>Días visibles</span></div></div></section>
<section className="intro" id="maintenance"><p className="eyebrow">MANTENIMIENTO, SIN COMPLICACIONES</p><div className="split"><h2>Entiende tu edificio<br/>de un vistazo.</h2><p>De una planilla técnica a una experiencia visual. Cada sistema tiene su frecuencia, proveedor y estado claramente identificado.</p></div></section>
<section className="systems">{community.systems.map((s,i)=><motion.article className="system" key={s.name} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:(i%3)*.08}}><div className="systemTop"><span className="ico">{s.icon}</span><span className={"badge "+label[s.status][1]}>{label[s.status][0]}</span></div><div><small>{s.frequency}</small><h3>{s.name}</h3><p>{s.note}</p></div><div className="provider"><span>Responsable</span><b>{s.provider}</b></div></motion.article>)}</section>
<section className="calendar"><div className="eyebrow">EL AÑO COMPLETO · EN UNA MIRADA</div><div className="split"><h2>Calendario<br/><em>que sí se entiende.</em></h2><p>Una lectura visual de las rutinas que mantienen funcionando tu comunidad. Verde: realizado. Ámbar: próximo. Todo lo demás, disponible cuando corresponda.</p></div><div className="months">{["ENE","FEB","MAR","ABR","MAY","JUN","JUL","AGO","SEP","OCT","NOV","DIC"].map((m,i)=><div className={"month "+(i===9?"active":"")} key={m}><span>{m}</span><div className="dots"><i/><i/><i/></div></div>)}</div></section>
<section className="providers"><p className="eyebrow">QUIÉNES CUIDAN TU COMUNIDAD</p><h2>Personas y empresas<br/>detrás de cada sistema.</h2><div className="providerGrid">{community.providers.map(p=><article className="providerCard" key={p.name}><div className="providerLogo">{p.name.slice(0,2).toUpperCase()}</div><small>{p.service}</small><h3>{p.name}</h3><p>{p.detail}</p>{p.web?<a href={p.web} target="_blank" rel="noreferrer">Conocer proveedor ↗</a>:<span className="pending">Información por validar</span>}</article>)}</div></section>
<section className="security"><div><p className="eyebrow">SEGURIDAD & CERTIFICACIONES</p><h2>Lo importante,<br/>siempre visible.</h2></div><div className="certs">{community.certifications.map(c=><article key={c.name}><span>{c.icon}</span><div><small>{c.frequency}</small><h3>{c.name}</h3><p>{c.state}</p></div></article>)}</div></section>
<section className="future"><div className="glow"/><p className="eyebrow">ESTO ES SOLO EL COMIENZO</p><h2>Hoy ves tu mantenimiento.<br/><em>Mañana, tu comunidad completa<br/>podría vivir aquí.</em></h2><div className="futureTags">{["Historial","Documentos","Activos","Avisos","Evidencias","Proveedores","Certificados","Comunidad"].map(x=><span key={x}>{x}<small>PRÓXIMAMENTE</small></span>)}</div><div className="signature"><div className="mark">O</div><div><b>ORBI CONDO</b><span>Smart Community Experience</span></div></div></section>
<footer><span>Concept experience · Parque Ciudadano II</span><span>Powered by ORBI Ecosystem · 2026</span></footer></main>}