"use client";
import {useState} from "react";
import {tally,type SurveyResponse,type Survey} from "../lib/community-voice";
const survey:Survey={id:"demo-community-day",communityId:"demo-pc2",question:"¿Qué horario prefieres para una actividad comunitaria?",description:"Consulta ilustrativa, sin validez de votación formal.",choices:[{id:"sat",label:"Sábado por la mañana"},{id:"sun",label:"Domingo por la tarde"},{id:"fri",label:"Viernes por la tarde"}],opensAt:"2030-01-01T00:00:00Z",closesAt:"2030-12-31T23:59:59Z",status:"published",createdBy:"demo-admin",approvedBy:"demo-committee"};
export default function CommunityVoice(){
 const [choice,setChoice]=useState("sat");
 const [submitted,setSubmitted]=useState(false);
 const [results,setResults]=useState(false);
 const responses:SurveyResponse[]=submitted?[{surveyId:survey.id,communityId:survey.communityId,respondentId:"demo-resident",choiceId:choice,submittedAt:"2030-06-01T12:00:00Z"}]:[];
 const counts=tally(survey,responses);
 return <section className="communityVoice" id="community-voice"><div className="moduleHead"><div><p className="eyebrow">ORBI COMMUNITY VOICE · PROTOTIPO</p><h2>Una comunidad<br/><em>que participa.</em></h2></div><p>Encuestas simples desde el teléfono, con publicación revisada por el comité y resultados comprensibles.</p></div><div className="moduleGrid"><div className="modulePanel"><div className="moduleStatus">ENCUESTA CONSULTIVA · DEMOSTRACIÓN</div><h3>{survey.question}</h3><p>{survey.description}</p>{!submitted?<fieldset className="voiceChoices"><legend>Selecciona una opción</legend>{survey.choices.map(c=><label key={c.id}><input type="radio" name="demo-voice" value={c.id} checked={choice===c.id} onChange={()=>setChoice(c.id)}/>{c.label}</label>)}</fieldset>:<div className="moduleNotice">Respuesta registrada únicamente en esta pantalla de ejemplo.</div>}<div className="moduleButtons">{!submitted?<button className="moduleAction" onClick={()=>{setSubmitted(true);setResults(true);}}>Responder en demo</button>:<button className="moduleAction secondary" onClick={()=>{setSubmitted(false);setResults(false);}}>Volver a probar</button>}<button className="moduleAction secondary" onClick={()=>setResults(r=>!r)}>{results?"Ocultar":"Ver"} resultados</button></div></div><div className="modulePanel"><p className="eyebrow">RESULTADOS · DEMOSTRACIÓN</p><h3>Visualización clara.</h3>{results?<div className="voiceResults">{counts.map(c=><div key={c.id}><div className="voiceResultLabel"><span>{c.label}</span><b>{c.votes}</b></div><div className="voiceTrack"><div style={{width:submitted&&c.votes?"100%":"0%"}}/></div></div>)}</div>:<p>Participa y consulta cómo se representarían las respuestas.</p>}<div className="moduleNotice">Sin respuestas reales ni almacenamiento. Para producción: identidad verificada, límite de participación, privacidad y separación de votaciones legales.</div></div></div></section>;
}
