"use client";
import {useState} from "react";
import {can,mayApplyChange,mayApproveChange,type Role,type ChangeRequest} from "../lib/governance";
const roleLabels:Record<Role,string>={administrator:"Administrador",committee:"Comité",resident:"Residente"};
export default function CondoGovernance(){
 const [role,setRole]=useState<Role>("administrator");
 const [request,setRequest]=useState<ChangeRequest>({id:"demo-change",communityId:"demo-pc2",createdBy:"admin-demo",status:"draft",kind:"schedule",reason:""});
 const [history,setHistory]=useState<string[]>([]);
 const actor=role==="administrator"?"admin-demo":role==="committee"?"committee-demo":"resident-demo";
 const transition=(status:ChangeRequest["status"],message:string)=>{setRequest(r=>({...r,status,approvedBy:status==="approved"?"committee-demo":r.approvedBy}));setHistory(h=>[message,...h]);};
 return <section className="governance" id="governance"><div className="moduleHead"><div><p className="eyebrow">ORBI CONDO ADMIN · PROTOTIPO</p><h2>Cambios con<br/><em>responsabilidad.</em></h2></div><p>El administrador propone y ejecuta. El comité revisa. El residente consulta. Simulación local sin cuentas ni cambios reales.</p></div><div className="moduleGrid"><div className="modulePanel"><label className="moduleLabel">Explorar perfil</label><div className="moduleSwitch">{(["administrator","committee","resident"] as Role[]).map(r=><button type="button" key={r} aria-pressed={role===r} className={role===r?"chosen":""} onClick={()=>setRole(r)}>{roleLabels[r]}</button>)}</div><div className="moduleStatus">SOLICITUD DEMO · {request.status.replaceAll("_"," ").toUpperCase()}</div><h3>Reprogramación de mantención</h3><p>Ejemplo de cambio que requiere revisión antes de modificar el calendario oficial.</p>{can(role,"propose_change")&&request.status==="draft"&&<><label className="moduleLabel" htmlFor="change-reason">Motivo de la modificación</label><textarea id="change-reason" value={request.reason} onChange={e=>setRequest(r=>({...r,reason:e.target.value}))} placeholder="Describe el motivo de la solicitud"/><button className="moduleAction" disabled={!request.reason.trim()} onClick={()=>transition("pending_committee","Administrador envió la propuesta al comité")}>Enviar al comité</button></>}{mayApproveChange(role,request,actor)&&<div className="moduleButtons"><button className="moduleAction" onClick={()=>transition("approved","Comité aprobó la solicitud")}>Aprobar</button><button className="moduleAction secondary" onClick={()=>transition("rejected","Comité rechazó la solicitud")}>Rechazar</button></div>}{mayApplyChange(role,request)&&<button className="moduleAction" onClick={()=>transition("applied","Administrador aplicó el cambio en esta simulación")}>Aplicar cambio simulado</button>}{request.status==="rejected"&&role==="administrator"&&<button className="moduleAction secondary" onClick={()=>{setRequest(r=>({...r,status:"draft",approvedBy:undefined}));setHistory(h=>["Administrador abrió una nueva revisión",...h]);}}>Revisar propuesta</button>}<button className="moduleReset" onClick={()=>{setRequest({id:"demo-change",communityId:"demo-pc2",createdBy:"admin-demo",status:"draft",kind:"schedule",reason:""});setHistory([]);}}>Reiniciar demostración</button></div><div className="modulePanel"><p className="eyebrow">TRAZABILIDAD</p><h3>Quién hizo qué.</h3><p>Los cambios oficiales necesitarán identidad verificada, respaldo, fecha y bitácora persistente.</p><ol className="moduleHistory">{history.length?history.map((h,i)=><li key={i}>{h}</li>):<li>Sin acciones en esta simulación</li>}</ol><div className="moduleNotice">Los botones solo modifican esta demostración en memoria. No existe todavía autenticación, base de datos ni edición operativa.</div></div></div></section>;
}
