import {HUELLA_COMMERCIAL_TYPES,HUELLA_PROMOTED_AMENITIES,HUELLA_SOURCE} from "../data/huella-commercial";
import {APARTMENT_TYPOLOGIES} from "../data/apartment-typologies";
const fmt=(n:number)=>n.toLocaleString("es-CL",{minimumFractionDigits:2,maximumFractionDigits:2});
export default function HuellaCommercialInfo(){
 return <section aria-labelledby="huella-title" style={{padding:"clamp(40px,6vw,90px) 6%",background:"#f1f7f5",color:"#163b3d"}}><div style={{maxWidth:1160,margin:"auto"}}>
 <p style={{letterSpacing:2,color:"#147d75",fontWeight:800}}>ARCHIVO COMERCIAL · FUENTE EXTERNA</p><h2 id="huella-title" style={{fontSize:"clamp(1.8rem,4vw,3.2rem)",margin:"12px 0"}}>Cinco tipologías documentadas.</h2><p>La inmobiliaria publica cinco tipos de departamentos. Las superficies comerciales se muestran separadas de los cuadros arquitectónicos de 2019; sus criterios y valores pueden diferir.</p>
 <div style={{overflowX:"auto",marginTop:22}}><table style={{borderCollapse:"collapse",width:"100%",minWidth:580,textAlign:"left"}}><thead><tr>{["Tipo","Distribución","Total comercial","Interior comercial","Terraza comercial","Total plano 2019"].map(h=><th key={h} style={{padding:12,borderBottom:"2px solid #7fa8a4"}}>{h}</th>)}</tr></thead><tbody>{HUELLA_COMMERCIAL_TYPES.map(t=>{const plan=APARTMENT_TYPOLOGIES.find(p=>p.id===t.id);return <tr key={t.id}><th scope="row" style={{padding:12,borderBottom:"1px solid #c4d7d4"}}>{t.id}</th><td style={{padding:12,borderBottom:"1px solid #c4d7d4"}}>{t.bedrooms}D · {t.bathrooms}B</td>{[t.totalM2,t.interiorM2,t.terraceM2].map((n,i)=><td key={i} style={{padding:12,borderBottom:"1px solid #c4d7d4",whiteSpace:"nowrap"}}>{fmt(n)} m²</td>)}<td style={{padding:12,borderBottom:"1px solid #c4d7d4",whiteSpace:"nowrap"}}>{plan?fmt(plan.totalBuiltM2)+" m²":"Plano pendiente"}</td></tr>})}</tbody></table></div>
 <h3 style={{marginTop:34}}>Plantas oficiales por tipología</h3>
 <p style={{color:"#456a68",lineHeight:1.7}}>Cada ficha conecta con la opción «Ver planta» publicada por Inmobiliaria Huella. Las imágenes permanecen en el sitio oficial; no se almacenan ni reproducen aquí sin autorización del titular.</p>
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,205px),1fr))",gap:14,marginTop:18}}>{HUELLA_COMMERCIAL_TYPES.map(t=><article key={t.id} style={{padding:20,border:"1px solid #b6d4cc",borderRadius:16,background:"white",display:"flex",flexDirection:"column",gap:12}}>
 <div aria-hidden="true" style={{height:115,borderRadius:10,background:"repeating-linear-gradient(0deg,transparent 0 24px,#cde0d9 25px),repeating-linear-gradient(90deg,#edf5f1 0 24px,#cde0d9 25px)",display:"grid",placeItems:"center",border:"1px solid #d4e5df"}}><span style={{background:"#fff",padding:"9px 14px",borderRadius:8,color:"#34625c",fontWeight:800}}>PLANTA {t.id}</span></div>
 <strong style={{fontSize:22}}>Tipo {t.id}</strong><span>{t.bedrooms} dormitorios · {t.bathrooms} baños</span><span style={{fontWeight:800}}>{fmt(t.totalM2)} m² comerciales</span>
 <a href={HUELLA_SOURCE.url+"#tipologias"} target="_blank" rel="noopener noreferrer" aria-label={"Ver planta oficial del departamento tipo "+t.id+" en Inmobiliaria Huella"} style={{marginTop:"auto",background:"#146e66",color:"white",padding:"12px 14px",borderRadius:9,textAlign:"center",fontWeight:800}}>Ver planta oficial ↗</a>
 </article>)}</div>
 <p style={{fontSize:12,color:"#4d716e"}}>La vista de cuadrícula es una representación gráfica de navegación, no el plano arquitectónico. En la página oficial, busca el botón «Ver planta» de la tipología correspondiente.</p>
 <h3 style={{marginTop:30}}>Equipamiento promocionado</h3><div style={{display:"flex",gap:9,flexWrap:"wrap"}}>{HUELLA_PROMOTED_AMENITIES.map(x=><span key={x} style={{padding:"8px 12px",borderRadius:99,background:"#dcebe7"}}>{x}</span>)}</div>
 <p style={{marginTop:22,fontSize:13,lineHeight:1.7}}>{HUELLA_SOURCE.caution} Las fotografías y planos comerciales permanecen en el sitio del titular hasta contar con autorización para reutilizarlos. No se presenta la información histórica de precios, créditos ni garantías como condiciones vigentes.</p>
 <a href={HUELLA_SOURCE.url} target="_blank" rel="noopener noreferrer" style={{display:"inline-block",marginTop:8,textDecoration:"underline",fontWeight:800}}>Consultar ficha oficial y planos comerciales ↗</a>
 </div></section>;
}
