import {HUELLA_COMMERCIAL_TYPES,HUELLA_PROMOTED_AMENITIES,HUELLA_SOURCE} from "../data/huella-commercial";
import {APARTMENT_TYPOLOGIES} from "../data/apartment-typologies";
const fmt=(n:number)=>n.toLocaleString("es-CL",{minimumFractionDigits:2,maximumFractionDigits:2});
export default function HuellaCommercialInfo(){
 return <section aria-labelledby="huella-title" style={{padding:"clamp(40px,6vw,90px) 6%",background:"#f1f7f5",color:"#163b3d"}}><div style={{maxWidth:1160,margin:"auto"}}>
 <p style={{letterSpacing:2,color:"#147d75",fontWeight:800}}>ARCHIVO COMERCIAL · FUENTE EXTERNA</p><h2 id="huella-title" style={{fontSize:"clamp(1.8rem,4vw,3.2rem)",margin:"12px 0"}}>Cinco tipologías documentadas.</h2><p>La inmobiliaria publica cinco tipos de departamentos. Las superficies comerciales se muestran separadas de los cuadros arquitectónicos de 2019; sus criterios y valores pueden diferir.</p>
 <div style={{overflowX:"auto",marginTop:22}}><table style={{borderCollapse:"collapse",width:"100%",minWidth:580,textAlign:"left"}}><thead><tr>{["Tipo","Distribución","Total comercial","Interior comercial","Terraza comercial","Total plano 2019"].map(h=><th key={h} style={{padding:12,borderBottom:"2px solid #7fa8a4"}}>{h}</th>)}</tr></thead><tbody>{HUELLA_COMMERCIAL_TYPES.map(t=>{const plan=APARTMENT_TYPOLOGIES.find(p=>p.id===t.id);return <tr key={t.id}><th scope="row" style={{padding:12,borderBottom:"1px solid #c4d7d4"}}>{t.id}</th><td style={{padding:12,borderBottom:"1px solid #c4d7d4"}}>{t.bedrooms}D · {t.bathrooms}B</td>{[t.totalM2,t.interiorM2,t.terraceM2].map((n,i)=><td key={i} style={{padding:12,borderBottom:"1px solid #c4d7d4",whiteSpace:"nowrap"}}>{fmt(n)} m²</td>)}<td style={{padding:12,borderBottom:"1px solid #c4d7d4",whiteSpace:"nowrap"}}>{plan?fmt(plan.totalBuiltM2)+" m²":"Plano pendiente"}</td></tr>})}</tbody></table></div>
 <h3 style={{marginTop:30}}>Equipamiento promocionado</h3><div style={{display:"flex",gap:9,flexWrap:"wrap"}}>{HUELLA_PROMOTED_AMENITIES.map(x=><span key={x} style={{padding:"8px 12px",borderRadius:99,background:"#dcebe7"}}>{x}</span>)}</div>
 <p style={{marginTop:22,fontSize:13,lineHeight:1.7}}>{HUELLA_SOURCE.caution} Las fotografías y planos comerciales permanecen en el sitio del titular hasta contar con autorización para reutilizarlos. No se presenta la información histórica de precios, créditos ni garantías como condiciones vigentes.</p>
 <a href={HUELLA_SOURCE.url} target="_blank" rel="noopener noreferrer" style={{display:"inline-block",marginTop:8,textDecoration:"underline",fontWeight:800}}>Consultar ficha oficial y planos comerciales ↗</a>
 </div></section>;
}
