"use client";
import {useState,type FormEvent} from "react";
import {validateEvidenceFiles,validateEvidenceMetadata} from "../lib/evidence";
export default function OrbiEvidence(){
 const [order,setOrder]=useState("");const [contractor,setContractor]=useState("");const [area,setArea]=useState("");const [asset,setAsset]=useState("");const [date,setDate]=useState("");const [summary,setSummary]=useState("");const [files,setFiles]=useState<File[]>([]);const [notice,setNotice]=useState("");
 function review(e:FormEvent<HTMLFormElement>){e.preventDefault();const errors=[...validateEvidenceMetadata({workOrderId:order,contractorName:contractor,area,asset,performedAt:date,summary}),...validateEvidenceFiles(files)];setNotice(errors.length?errors.join(" "):"Vista previa validada. No se han subido archivos, enviado correos ni registrado un mantenimiento.");}
 const fieldStyle={width:"100%",padding:12,borderRadius:9,border:"1px solid #a7c6c9",background:"#fff",color:"#102b35"};
 return <section id="orbi-evidence" aria-labelledby="evidence-title" style={{padding:"clamp(36px,6vw,90px) 6%",background:"#102c36",color:"#f5fffe"}}>
 <div style={{maxWidth:960,margin:"auto"}}><p style={{letterSpacing:2,color:"#71e8db",fontWeight:800}}>ORBI EVIDENCE · PROTOTIPO</p><h2 id="evidence-title" style={{fontSize:"clamp(2rem,4vw,3.4rem)",margin:"12px 0"}}>Cada trabajo. Una evidencia verificable.</h2><p style={{lineHeight:1.7,maxWidth:720}}>Registro obligatorio de fotografías de cada trabajo de mantenimiento; los informes técnicos son complementarios y nunca sustituyen las fotos. Siempre que corresponda, adjunta imágenes del antes, durante y después. En producción, cada entrega requerirá una invitación segura vinculada a una orden de trabajo y revisión del administrador antes de publicarse.</p>
 <form onSubmit={review} style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,280px),1fr))",gap:16,marginTop:26}}>
 {([{id:"ev-order",label:"Orden de trabajo",value:order,set:setOrder,placeholder:"OT-001"},{id:"ev-contractor",label:"Contratista",value:contractor,set:setContractor,placeholder:"Empresa ejecutora"},{id:"ev-area",label:"Especialidad",value:area,set:setArea,placeholder:"Ascensores, bombas, CCTV…"},{id:"ev-asset",label:"Equipo o instalación",value:asset,set:setAsset,placeholder:"Ascensor torre A"}] as const).map(f=><div key={f.id} style={{display:"grid",gap:7}}><label htmlFor={f.id}>{f.label}</label><input id={f.id} value={f.value} onChange={e=>{f.set(e.target.value);setNotice("")}} placeholder={f.placeholder} maxLength={120} required style={fieldStyle}/></div>)}
 <div style={{display:"grid",gap:7}}><label htmlFor="ev-date">Fecha de ejecución</label><input id="ev-date" type="date" value={date} onChange={e=>{setDate(e.target.value);setNotice("")}} required style={fieldStyle}/></div>
 <div style={{display:"grid",gap:7}}><label htmlFor="ev-files">Fotografías obligatorias + informes opcionales (JPG, PNG, WEBP, PDF; máximo 12 archivos de 10 MB)</label><input id="ev-files" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" multiple onChange={e=>{setFiles(Array.from(e.target.files??[]));setNotice("")}} required style={{...fieldStyle,color:"#fff",background:"transparent"}}/></div>
 <div style={{gridColumn:"1 / -1",display:"grid",gap:7}}><label htmlFor="ev-summary">Trabajo ejecutado y observaciones</label><textarea id="ev-summary" value={summary} onChange={e=>{setSummary(e.target.value);setNotice("")}} maxLength={500} rows={3} required style={fieldStyle}/></div>
 <div style={{gridColumn:"1 / -1"}}><button type="submit" style={{background:"#71e8db",color:"#08252e",padding:"14px 22px",border:0,borderRadius:9,fontWeight:800,cursor:"pointer"}}>Revisar entrega (demo)</button>{notice&&<p role="status" style={{marginTop:12}}>{notice}</p>}</div>
 </form><p style={{marginTop:20,color:"#b2d5d7"}}>Flujo previsto: contratista entrega → administrador revisa → publicación autorizada → comunidad consulta. No se crea un cuarto perfil.</p></div></section>;
}
