"use client";
import {useMemo,useState} from "react";
import {LIBRARY_CATEGORIES,LIBRARY_DOCUMENTS,type TechnicalCategory} from "../data/technical-library";
export default function TechnicalLibrary(){
 const [category,setCategory]=useState<TechnicalCategory|"Todas">("Todas");
 const [search,setSearch]=useState("");
 const filtered=useMemo(()=>LIBRARY_DOCUMENTS.filter(d=>(category==="Todas"||d.category===category)&&[d.title,d.description,d.source,d.category,...(d.types??[])].join(" ").toLocaleLowerCase("es-CL").includes(search.trim().toLocaleLowerCase("es-CL"))),[category,search]);
 const available=LIBRARY_DOCUMENTS.filter(d=>d.verification!=="Pendiente de documento").length;
 return <section id="biblioteca-tecnica" aria-labelledby="library-title" style={{padding:"clamp(48px,7vw,100px) 6%",background:"#081b20",color:"#eafffa"}}><div style={{maxWidth:1160,margin:"auto"}}>
 <p style={{fontSize:12,letterSpacing:2,color:"#7ce5d0",fontWeight:800}}>ORBI LIVING · ARCHIVO EN EVOLUCIÓN</p><h2 id="library-title" style={{fontSize:"clamp(2rem,4.5vw,3.5rem)",margin:"12px 0"}}>Biblioteca Técnica</h2><p style={{maxWidth:790,lineHeight:1.7,color:"#bad4d1"}}>Un registro organizado de los documentos del condominio, sus fuentes y su estado de validación. Los documentos restringidos no se descargan desde esta versión pública.</p>
 <p aria-live="polite" style={{color:"#92ebd9",fontWeight:800}}>{LIBRARY_DOCUMENTS.length} registros · {available} fuentes identificadas o referenciales · {LIBRARY_DOCUMENTS.length-available} documentos pendientes</p>
 <div style={{display:"flex",flexWrap:"wrap",gap:12,margin:"26px 0"}}><label style={{flex:"2 1 250px"}}><span style={{display:"block",marginBottom:7}}>Buscar documento</span><input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Ej.: plano, ascensor, C3..." style={{width:"100%",padding:13,border:"1px solid #528a86",borderRadius:10,background:"#102e33",color:"white",fontSize:16}}/></label><label style={{flex:"1 1 220px"}}><span style={{display:"block",marginBottom:7}}>Categoría</span><select value={category} onChange={e=>setCategory(e.target.value as TechnicalCategory|"Todas")} style={{width:"100%",padding:13,border:"1px solid #528a86",borderRadius:10,background:"#102e33",color:"white",fontSize:16}}><option value="Todas">Todas las categorías</option>{LIBRARY_CATEGORIES.map(c=><option key={c} value={c}>{c}</option>)}</select></label></div>
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,310px),1fr))",gap:15}}>{filtered.map(d=><article key={d.id} style={{padding:22,border:"1px solid #356a6a",borderRadius:15,background:"#102c32",display:"flex",flexDirection:"column",gap:11}}>
 <div style={{display:"flex",gap:8,justifyContent:"space-between",flexWrap:"wrap"}}><span style={{color:"#84edda",fontSize:12,fontWeight:800}}>{d.category}</span><span style={{color:d.verification==="Pendiente de documento"?"#f3d49b":"#c0e4d9",fontSize:12}}>{d.verification}</span></div><h3 style={{fontSize:19,margin:0}}>{d.title}</h3><p style={{lineHeight:1.6,margin:0,color:"#c4dad7"}}>{d.description}</p>
 <dl style={{fontSize:13,display:"grid",gridTemplateColumns:"auto 1fr",gap:"7px 12px",margin:"auto 0 0"}}><dt>Fuente</dt><dd style={{margin:0}}>{d.source}</dd><dt>Fecha</dt><dd style={{margin:0}}>{d.dateLabel}</dd><dt>Versión</dt><dd style={{margin:0}}>{d.version}</dd><dt>Formato</dt><dd style={{margin:0}}>{d.format}</dd><dt>Acceso</dt><dd style={{margin:0}}>{d.access}</dd></dl>
 {d.url&&d.access==="Público"?<a href={d.url} target="_blank" rel="noopener noreferrer" style={{marginTop:8,color:"#8df5e1",textDecoration:"underline",fontWeight:800}}>Consultar fuente original ↗</a>:<span style={{fontSize:12,color:"#a6c3c0",marginTop:8}}>Archivo no disponible para descarga pública</span>}
 </article>)}</div>{filtered.length===0&&<p role="status">No hay documentos que coincidan con los filtros seleccionados.</p>}
 <p style={{marginTop:24,fontSize:13,color:"#abc9c5",lineHeight:1.7}}>Los estados describen la procedencia de los registros, no certifican su vigencia técnica. Nuevos archivos se incorporarán tras revisar versión, fuente, privacidad y autorización de publicación. Esta biblioteca es informativa y no reemplaza el expediente oficial del condominio.</p>
 </div></section>;
}
